baseURL = "https://videogamemakers.page/"
theme = "hugo-theme-codex"
languageCode = "en-us"
title = "Effects of Public Funding in Indie Video Game Development: Australia and the UK"
enableEmoji = true
copyright = "© 2020−2025. Raman Voranau, raman.voranau@mymail.unisa.edu.au"
publishdir = "docs"

[params]
author = "Raman Voranau"
description = "I interview video game makers from Australia studying their leisure time."
favicon = "favicon.ico"
twitter = "https://twitter.com/ramanvoranau"
github = "https://github.com/voranau"
showPageTitleInTOC = false
[params.footer]
text = "By Raman Voranau"
url = "https://github.com/voranau"

[permalinks]
"/" = "/:filename"

[menu]
[[menu.main]]
identifier = "researcher"
name = "Researcher"
url = "/researcher"
weight = 5
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[markup.goldmark.renderer]
unsafe = true # allow raw HTML in markdown files
